### ISSUE TITLE
`_insensitivize_dicts` not called

### ISSUE THREAD

**Issue by Gr1N** [admiralobvious/vyper#1]
Hi,

First, thanks for the library. And now I'm going to introduce your first bug :)

See an example:
```
# config.yaml
Service:
  Name: test

# main.py
v = Viper()
v.set_config_type('yaml')
v.set_config_name('config')
v.add_config_path('.')
v.read_in_config()

print(v.get('service'))
# => None
```

As I see problem is very simple, method `_insensitivize_dicts` never called.

**Comment by admiralobvious** [comment]
Thanks! Sorry for the late reply, holidays you know. :)
I'll make a new release with this fix ASAP.
