### ISSUE TITLE
Overlaying configurations

### ISSUE THREAD

**Issue by edupo** [admiralobvious/vyper#23]
I have a use case where I want to overlay configurations. By overlay I mean loading several configs from files named but those are in different paths:
Some config is on `%APPDATA%` and some other will be on the `cwd`.

I found a way implementing my own helper method to load and merge in sequentially different files, but I'm wondering why this isn't a feature.

What do you think?

**Comment by admiralobvious** [comment]
There's no specific reason why this isn't a feature other than [viper](https://github.com/spf13/viper) doesn't support it and I never thought of/needed that feature myself.

What's your use case?
