### ISSUE TITLE
Conflicting Dependencies in 0.3.x versions.

### ISSUE THREAD

**Issue by jperkelens** [admiralobvious/vyper#24]
The requirement of `future==0.17.1` is directly in conflict with [Airflow's 1.10.3 requirements](https://github.com/apache/airflow/blob/e1c1a8dad0e01a7baa50ebe02e748429d33241fd/setup.py#L326). We can remain on 0.2.3 without too much problem but I wonder if its worth following the advice set out in the "security reasons" section of this [proposal](https://github.com/pypa/pipenv/issues/1911): 

> With development of python library one cannot achieve such security, because libraries must not define concrete dependencies. Breaking this rule (thus trying to declare concrete dependencies by python library) results in problems such as:
> * problems to find satisfying version of shared libraries (each strict package defines exact version of shared library and it is very likely the versions will differ and prevent finding commonly acceptable version)
> * concrete dependencies may depend on python version, OS or other environment markers and trying to install the package in diferent context can easily fail to satisfy some of rules defined in original abstract dependencies.

**Comment by admiralobvious** [comment]
Fixed in v0.4.0 but this release also removes Python 2.7 support, are you on still on it?

**Comment by jperkelens** [comment]
no we've been on Python 3 for a while. Thanks so much! will upgrade soon.
