### ISSUE TITLE
Repository seems to have fallen out of maintenance.

### ISSUE THREAD

**Issue by jperkelens** [admiralobvious/vyper#36]
Hi, it seems like this repository has fallen out of maintenance. I'm happy to assume ownership of it as we use it extensively. Please let me know if this is something you're interested in.

**Comment by admiralobvious** [comment]
Hi! Yeah I guess I dropped the ball a bit as it's been working great for my work. I merged the outstanding PRs and will prepare a release ASAP. Do you have any other outstanding issues?

**Comment by jperkelens** [comment]
Not at the moment! But will certainly keep you posted. If you'd like help
with maintenance, without transferring ownership, I'm more than willing to
lend a hand there.

**Comment by jperkelens** [comment]
Actually, there is one thing i just noticed, but I can have a PR for that momentarily
