### ISSUE TITLE
[Support cmd args]  Architecture / Implementation question

### ISSUE THREAD

**Issue by benjaminch** [admiralobvious/vyper#4]
Hello Guys,

I saw that cmd args support is not here yet. I am wondering if you had any idea / plan about how to implement it in this library?
Happy to know more about your ideas around that so we maybe help you with that.

Cheers

**Comment by admiralobvious** [comment]
Hello!

This is already something that can be done with a bit of extra code. See my boilerplate project for Falcon [here](https://github.com/admiralobvious/falcon-boilerplate).

[setup vyper](https://github.com/admiralobvious/falcon-boilerplate/blob/master/app/__init__.py#L15)
[cmd args defined here](https://github.com/admiralobvious/falcon-boilerplate/blob/master/app/config.py)
[code that glues everything together](https://github.com/admiralobvious/falcon-boilerplate/blob/master/app/util/config.py)

I will add a smaller version of this in the examples folder though and I could maybe add it to Vyper itself.

**Comment by benjaminch** [comment]
Hello Guys, 

I just submitted a draft PR to include flags support into vyper.
Let me know what you think :) 

Thanks !

**Comment by benjaminch** [comment]
Hey @admiralobvious, did you get a chance to look at the PR ?

Cheers

**Comment by admiralobvious** [comment]
merged

**Comment by benjaminch** [comment]
Thanks a lot ! :)
